FROM node:16.6-alpine3.14

RUN apk add ca-certificates

COPY package.json .
COPY yarn.lock .
COPY packages/tests/ ./packages/tests/

RUN yarn workspace tests install --frozen-lockfile

WORKDIR ./packages/tests/
ENV NODE_EXTRA_CA_CERTS=/var/run/secrets/tokens/ca.crt
ENTRYPOINT yarn start
